services:
  webapi:
    build: ./webapi
    container_name: webapi
    expose:
      - "5000"
    restart: unless-stopped

  apache:
    build: ./apache
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./apache/my-proxy.conf:/usr/local/apache2/conf/extra/my-proxy.conf:ro
    depends_on:
      - webapi
    restart: unless-stopped

